name: Test `list-artifacts` action
on:
  push:
    branches:
      - main

jobs:
  test-list-artifacts:
    runs-on: ['ubuntu-latest']
    name: Test
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare artifact
        run: |
          echo "test" > file.txt
          echo "test2" > file2.txt
      - name: 'Upload artifact #1'
        uses: actions/upload-artifact@v4
        with:
          name: test-1
          path: file.txt
      - name: 'Upload artifact #2'
        uses: actions/upload-artifact@v4
        with:
          name: test-2
          path: file2.txt
      - name: List artifacts
        id: list
        uses: ./
        with:
          name: test-*
      - name: Select names only
        uses: yakubique/json-utils@v1.3
        id: names
        with:
          input: ${{ steps.list.outputs.result }}
          action: 'get'
          key: 'name'
      - name: Check
        run: |
          echo "${{ steps.names.outputs.result }}"
          test "${{ steps.names.outputs.result }}" = "[test-2,test-1]"
      - uses: geekyeggo/delete-artifact@v4
        name: Clean UP
        with:
          failOnError: false
          name: |
            test-1
            test-2
